/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// EventEntity struct for EventEntity
type EventEntity struct {
	Id         string            `json:"id,omitempty"`
	Type       string            `json:"type,omitempty"`
	Payload    string            `json:"payload,omitempty"`
	ParentId   string            `json:"parentId,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	User       UserEntity        `json:"user,omitempty"`
	CreatedAt  int64             `json:"created_at,omitempty"`
	UpdatedAt  int64             `json:"updated_at,omitempty"`
}
