/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Failover struct for Failover
type Failover struct {
	MaxAttempts  int32    `json:"maxAttempts,omitempty"`
	RetryTimeout int64    `json:"retryTimeout,omitempty"`
	Cases        []string `json:"cases,omitempty"`
}
