/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// NewMetadataEntity struct for NewMetadataEntity
type NewMetadataEntity struct {
	Name   string `json:"name"`
	Format string `json:"format,omitempty"`
	Value  string `json:"value,omitempty"`
	Hidden bool   `json:"hidden,omitempty"`
}
