/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PolicyDevelopmentEntity struct for PolicyDevelopmentEntity
type PolicyDevelopmentEntity struct {
	Class              string `json:"class,omitempty"`
	ConfigurationClass string `json:"configuration_class,omitempty"`
	OnRequestMethod    string `json:"on_request_method,omitempty"`
	OnResponseMethod   string `json:"on_response_method,omitempty"`
}
