/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// ApplicationEntity struct for ApplicationEntity
type ApplicationEntity struct {
	Id          string             `json:"id,omitempty"`
	Name        string             `json:"name,omitempty"`
	Description string             `json:"description,omitempty"`
	Type        string             `json:"type,omitempty"`
	Groups      []string           `json:"groups,omitempty"`
	Status      string             `json:"status,omitempty"`
	Role        string             `json:"role,omitempty"`
	ClientId    string             `json:"clientId,omitempty"`
	CreatedAt   int64              `json:"created_at,omitempty"`
	UpdatedAt   int64              `json:"updated_at,omitempty"`
	Owner       PrimaryOwnerEntity `json:"owner,omitempty"`
}
