/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PageEntity struct for PageEntity
type PageEntity struct {
	Id                   string            `json:"id,omitempty"`
	Name                 string            `json:"name,omitempty"`
	Type                 string            `json:"type,omitempty"`
	Content              string            `json:"content,omitempty"`
	Order                int32             `json:"order,omitempty"`
	LastContributor      string            `json:"lastContributor,omitempty"`
	Published            bool              `json:"published,omitempty"`
	LastModificationDate int64             `json:"lastModificationDate,omitempty"`
	ContentType          string            `json:"contentType,omitempty"`
	Source               PageSourceEntity  `json:"source,omitempty"`
	Configuration        map[string]string `json:"configuration,omitempty"`
	Homepage             bool              `json:"homepage,omitempty"`
	ParentId             string            `json:"parentId,omitempty"`
	ExcludedGroups       []string          `json:"excluded_groups,omitempty"`
}
