/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// EndpointGroup struct for EndpointGroup
type EndpointGroup struct {
	Name         string       `json:"name,omitempty"`
	Endpoints    []Endpoint   `json:"endpoints,omitempty"`
	LoadBalancer LoadBalancer `json:"loadBalancer,omitempty"`
	Services     Services     `json:"services,omitempty"`
}
