/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UpdateEntryPointEntity struct for UpdateEntryPointEntity
type UpdateEntryPointEntity struct {
	Id    string   `json:"id,omitempty"`
	Value string   `json:"value"`
	Tags  []string `json:"tags"`
}
