/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UserGroupEntity struct for UserGroupEntity
type UserGroupEntity struct {
	Id    string            `json:"id,omitempty"`
	Name  string            `json:"name,omitempty"`
	Roles map[string]string `json:"roles,omitempty"`
}
