/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// RatingEntity struct for RatingEntity
type RatingEntity struct {
	Id              string               `json:"id,omitempty"`
	Api             string               `json:"api,omitempty"`
	User            string               `json:"user,omitempty"`
	UserDisplayName string               `json:"userDisplayName,omitempty"`
	Rate            string               `json:"rate,omitempty"`
	Title           string               `json:"title,omitempty"`
	Comment         string               `json:"comment,omitempty"`
	CreatedAt       int64                `json:"createdAt,omitempty"`
	UpdatedAt       int64                `json:"updatedAt,omitempty"`
	Answers         []RatingAnswerEntity `json:"answers,omitempty"`
}
