/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// SearchableUser struct for SearchableUser
type SearchableUser struct {
	DisplayName string `json:"displayName,omitempty"`
	Reference   string `json:"reference,omitempty"`
	Firstname   string `json:"firstname,omitempty"`
	Lastname    string `json:"lastname,omitempty"`
	Id          string `json:"id,omitempty"`
}
