/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Portal struct for Portal
type Portal struct {
	Title        string            `json:"title,omitempty"`
	Entrypoint   string            `json:"entrypoint,omitempty"`
	ApikeyHeader string            `json:"apikeyHeader,omitempty"`
	Support      Enabled           `json:"support,omitempty"`
	DevMode      Enabled           `json:"devMode,omitempty"`
	UserCreation Enabled           `json:"userCreation,omitempty"`
	Apis         PortalApis        `json:"apis,omitempty"`
	Analytics    PortalAnalytics   `json:"analytics,omitempty"`
	Dashboard    PortalDashboard   `json:"dashboard,omitempty"`
	Rating       PortalRating      `json:"rating,omitempty"`
	UploadMedia  PortalUploadMedia `json:"uploadMedia,omitempty"`
}
