/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// NewTicketEntity struct for NewTicketEntity
type NewTicketEntity struct {
	Subject      string `json:"subject"`
	Content      string `json:"content"`
	Application  string `json:"application,omitempty"`
	Api          string `json:"api,omitempty"`
	CopyToSender bool   `json:"copyToSender,omitempty"`
}
