/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UpdatePageEntity struct for UpdatePageEntity
type UpdatePageEntity struct {
	Name            string            `json:"name"`
	Content         string            `json:"content,omitempty"`
	LastContributor string            `json:"lastContributor,omitempty"`
	Order           int32             `json:"order,omitempty"`
	Published       bool              `json:"published,omitempty"`
	Source          PageSourceEntity  `json:"source,omitempty"`
	Configuration   map[string]string `json:"configuration,omitempty"`
	Homepage        bool              `json:"homepage,omitempty"`
	ParentId        string            `json:"parentId,omitempty"`
	ExcludedGroups  []string          `json:"excluded_groups,omitempty"`
}
