/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// OAuth2Authentication struct for OAuth2Authentication
type OAuth2Authentication struct {
	ClientId              string   `json:"clientId,omitempty"`
	Name                  string   `json:"name,omitempty"`
	Color                 string   `json:"color,omitempty"`
	AuthorizationEndpoint string   `json:"authorizationEndpoint,omitempty"`
	UserLogoutEndpoint    string   `json:"userLogoutEndpoint,omitempty"`
	Scope                 []string `json:"scope,omitempty"`
}
