/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Scheduler struct for Scheduler
type Scheduler struct {
	Tasks         int32 `json:"tasks,omitempty"`
	Notifications int32 `json:"notifications,omitempty"`
}
