/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PageEventEntity struct for PageEventEntity
type PageEventEntity struct {
	Content       []EventEntity `json:"content,omitempty"`
	PageElements  int64         `json:"pageElements,omitempty"`
	PageNumber    int32         `json:"pageNumber,omitempty"`
	TotalElements int64         `json:"totalElements,omitempty"`
}
