/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Properties struct for Properties
type Properties struct {
	Properties []Property        `json:"properties,omitempty"`
	Values     map[string]string `json:"values,omitempty"`
}
