/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PlanEntity struct for PlanEntity
type PlanEntity struct {
	Id                 string          `json:"id,omitempty"`
	Name               string          `json:"name,omitempty"`
	Description        string          `json:"description,omitempty"`
	Validation         string          `json:"validation,omitempty"`
	Security           string          `json:"security,omitempty"`
	SecurityDefinition string          `json:"securityDefinition,omitempty"`
	Type               string          `json:"type,omitempty"`
	Status             string          `json:"status,omitempty"`
	Apis               []string        `json:"apis,omitempty"`
	Order              int32           `json:"order,omitempty"`
	Characteristics    []string        `json:"characteristics,omitempty"`
	CreatedAt          int64           `json:"created_at,omitempty"`
	UpdatedAt          int64           `json:"updated_at,omitempty"`
	PublishedAt        int64           `json:"published_at,omitempty"`
	ClosedAt           int64           `json:"closed_at,omitempty"`
	Paths              map[string]Path `json:"paths"`
	ExcludedGroups     []string        `json:"excluded_groups,omitempty"`
	CommentRequired    bool            `json:"comment_required,omitempty"`
}
