/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UpdateIdentityProviderEntity struct for UpdateIdentityProviderEntity
type UpdateIdentityProviderEntity struct {
	Name               string                            `json:"name"`
	Description        string                            `json:"description,omitempty"`
	Configuration      map[string]map[string]interface{} `json:"configuration"`
	Enabled            bool                              `json:"enabled"`
	GroupMappings      []GroupMappingEntity              `json:"groupMappings,omitempty"`
	RoleMappings       []RoleMappingEntity               `json:"roleMappings,omitempty"`
	UserProfileMapping map[string]string                 `json:"userProfileMapping,omitempty"`
}
