/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Logging struct for Logging
type Logging struct {
	Mode      string `json:"mode,omitempty"`
	Condition string `json:"condition,omitempty"`
}
