/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Property struct for Property
type Property struct {
	Key     string `json:"key,omitempty"`
	Value   string `json:"value,omitempty"`
	Dynamic bool   `json:"dynamic,omitempty"`
}
