/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// RoleEntity struct for RoleEntity
type RoleEntity struct {
	Name        string              `json:"name,omitempty"`
	Description string              `json:"description,omitempty"`
	Scope       string              `json:"scope,omitempty"`
	System      bool                `json:"system,omitempty"`
	Permissions map[string][]string `json:"permissions,omitempty"`
	Default     bool                `json:"default,omitempty"`
}
