/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// GroupMemberEntity struct for GroupMemberEntity
type GroupMemberEntity struct {
	Id          string            `json:"id,omitempty"`
	DisplayName string            `json:"displayName,omitempty"`
	Roles       map[string]string `json:"roles,omitempty"`
	CreatedAt   int64             `json:"created_at,omitempty"`
	UpdatedAt   int64             `json:"updated_at,omitempty"`
}
