/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UpdateGroupEntity struct for UpdateGroupEntity
type UpdateGroupEntity struct {
	Name       string                 `json:"name"`
	Roles      map[string]string      `json:"roles,omitempty"`
	EventRules []GroupEventRuleEntity `json:"event_rules,omitempty"`
}
