/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// GenericNotificationConfigEntity struct for GenericNotificationConfigEntity
type GenericNotificationConfigEntity struct {
	Id             string   `json:"id,omitempty"`
	Name           string   `json:"name,omitempty"`
	ReferenceType  string   `json:"referenceType,omitempty"`
	ReferenceId    string   `json:"referenceId,omitempty"`
	Notifier       string   `json:"notifier,omitempty"`
	Config         string   `json:"config,omitempty"`
	Hooks          []string `json:"hooks,omitempty"`
	UseSystemProxy bool     `json:"useSystemProxy,omitempty"`
	ConfigType     string   `json:"config_type,omitempty"`
}
