/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// ApiListItem struct for ApiListItem
type ApiListItem struct {
	Id              string             `json:"id,omitempty"`
	Name            string             `json:"name,omitempty"`
	Version         string             `json:"version,omitempty"`
	Description     string             `json:"description,omitempty"`
	Visibility      string             `json:"visibility,omitempty"`
	State           string             `json:"state,omitempty"`
	Role            string             `json:"role,omitempty"`
	Views           []string           `json:"views,omitempty"`
	Labels          []string           `json:"labels,omitempty"`
	Manageable      bool               `json:"manageable,omitempty"`
	Rate            float64            `json:"rate,omitempty"`
	NumberOfRatings int32              `json:"numberOfRatings,omitempty"`
	Tags            []string           `json:"tags,omitempty"`
	CreatedAt       int64              `json:"created_at,omitempty"`
	UpdatedAt       int64              `json:"updated_at,omitempty"`
	Owner           PrimaryOwnerEntity `json:"owner,omitempty"`
	PictureUrl      string             `json:"picture_url,omitempty"`
	ContextPath     string             `json:"context_path,omitempty"`
}
