/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PortalUploadMedia struct for PortalUploadMedia
type PortalUploadMedia struct {
	Enabled        bool  `json:"enabled,omitempty"`
	MaxSizeInOctet int32 `json:"maxSizeInOctet,omitempty"`
}
