/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// ApiQualityMetricsEntity struct for ApiQualityMetricsEntity
type ApiQualityMetricsEntity struct {
	Score         float64         `json:"score,omitempty"`
	MetricsPassed map[string]bool `json:"metrics_passed,omitempty"`
}
