/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Payload struct for Payload
type Payload struct {
	ClientId    string `json:"clientId,omitempty"`
	RedirectUri string `json:"redirectUri,omitempty"`
	Code        string `json:"code,omitempty"`
	State       string `json:"state,omitempty"`
}
