/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UserRoleEntity struct for UserRoleEntity
type UserRoleEntity struct {
	Name        string              `json:"name,omitempty"`
	Scope       string              `json:"scope,omitempty"`
	Permissions map[string][]string `json:"permissions,omitempty"`
}
