/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// MemberEntity struct for MemberEntity
type MemberEntity struct {
	Id          string              `json:"id,omitempty"`
	DisplayName string              `json:"displayName,omitempty"`
	Email       string              `json:"email,omitempty"`
	Role        string              `json:"role,omitempty"`
	Permissions map[string][]string `json:"permissions,omitempty"`
	CreatedAt   int64               `json:"created_at,omitempty"`
	UpdatedAt   int64               `json:"updated_at,omitempty"`
}
