/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// ApiMembership struct for ApiMembership
type ApiMembership struct {
	// User's technical identifier.
	Id string `json:"id,omitempty"`
	// User's reference for user providing from an identity provider.
	Reference string `json:"reference,omitempty"`
	// Role's name
	Role string `json:"role"`
}
