/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PortalConfigEntity struct for PortalConfigEntity
type PortalConfigEntity struct {
	Company           Company           `json:"company,omitempty"`
	Management        Management        `json:"management,omitempty"`
	Portal            Portal            `json:"portal,omitempty"`
	Authentication    Authentication    `json:"authentication,omitempty"`
	Scheduler         Scheduler         `json:"scheduler,omitempty"`
	Documentation     Documentation     `json:"documentation,omitempty"`
	Theme             Theme             `json:"theme,omitempty"`
	Plan              Plan              `json:"plan,omitempty"`
	ApiQualityMetrics ApiQualityMetrics `json:"apiQualityMetrics,omitempty"`
}
