/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Plan struct for Plan
type Plan struct {
	Id       string `json:"id,omitempty"`
	Name     string `json:"name,omitempty"`
	Security string `json:"security,omitempty"`
}
