/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// NewPlanEntity struct for NewPlanEntity
type NewPlanEntity struct {
	Name               string          `json:"name"`
	Description        string          `json:"description"`
	Validation         string          `json:"validation"`
	Security           string          `json:"security"`
	SecurityDefinition string          `json:"securityDefinition,omitempty"`
	Type               string          `json:"type"`
	Status             string          `json:"status"`
	Api                string          `json:"api,omitempty"`
	Characteristics    []string        `json:"characteristics,omitempty"`
	Paths              map[string]Path `json:"paths"`
	ExcludedGroups     []string        `json:"excluded_groups,omitempty"`
	CommentRequired    bool            `json:"comment_required,omitempty"`
}
