/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Page struct for Page
type Page struct {
	Current       int32 `json:"current,omitempty"`
	Size          int32 `json:"size,omitempty"`
	PerPage       int32 `json:"per_page,omitempty"`
	TotalPages    int32 `json:"total_pages,omitempty"`
	TotalElements int32 `json:"total_elements,omitempty"`
}
