/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Proxy struct for Proxy
type Proxy struct {
	ContextPath      string          `json:"contextPath,omitempty"`
	Groups           []EndpointGroup `json:"groups,omitempty"`
	Failover         Failover        `json:"failover,omitempty"`
	Cors             Cors            `json:"cors,omitempty"`
	Logging          Logging         `json:"logging,omitempty"`
	StripContextPath bool            `json:"stripContextPath,omitempty"`
}
