/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// IdentityProviderEntity struct for IdentityProviderEntity
type IdentityProviderEntity struct {
	Id                 string                            `json:"id,omitempty"`
	Name               string                            `json:"name,omitempty"`
	Description        string                            `json:"description,omitempty"`
	Type               string                            `json:"type,omitempty"`
	Enabled            bool                              `json:"enabled,omitempty"`
	Configuration      map[string]map[string]interface{} `json:"configuration,omitempty"`
	GroupMappings      []GroupMappingEntity              `json:"groupMappings,omitempty"`
	RoleMappings       []RoleMappingEntity               `json:"roleMappings,omitempty"`
	UserProfileMapping map[string]string                 `json:"userProfileMapping,omitempty"`
	CreatedAt          int64                             `json:"created_at,omitempty"`
	UpdatedAt          int64                             `json:"updated_at,omitempty"`
}
