/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// ApiMetadataEntity struct for ApiMetadataEntity
type ApiMetadataEntity struct {
	Key          string `json:"key"`
	Name         string `json:"name,omitempty"`
	Format       string `json:"format,omitempty"`
	Value        string `json:"value"`
	DefaultValue string `json:"defaultValue,omitempty"`
	ApiId        string `json:"apiId,omitempty"`
}
