/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// ApiRequest struct for ApiRequest
type ApiRequest struct {
	Id                    string                       `json:"id,omitempty"`
	Timestamp             int64                        `json:"timestamp,omitempty"`
	TransactionId         string                       `json:"transactionId,omitempty"`
	Uri                   string                       `json:"uri,omitempty"`
	Path                  string                       `json:"path,omitempty"`
	Method                string                       `json:"method,omitempty"`
	Status                int32                        `json:"status,omitempty"`
	ResponseTime          int64                        `json:"responseTime,omitempty"`
	ApiResponseTime       int64                        `json:"apiResponseTime,omitempty"`
	RequestContentLength  int64                        `json:"requestContentLength,omitempty"`
	ResponseContentLength int64                        `json:"responseContentLength,omitempty"`
	ApiKey                string                       `json:"apiKey,omitempty"`
	Plan                  string                       `json:"plan,omitempty"`
	Application           string                       `json:"application,omitempty"`
	LocalAddress          string                       `json:"localAddress,omitempty"`
	RemoteAddress         string                       `json:"remoteAddress,omitempty"`
	Endpoint              string                       `json:"endpoint,omitempty"`
	Tenant                string                       `json:"tenant,omitempty"`
	ClientRequest         Request                      `json:"clientRequest,omitempty"`
	ProxyRequest          Request                      `json:"proxyRequest,omitempty"`
	ClientResponse        Response                     `json:"clientResponse,omitempty"`
	ProxyResponse         Response                     `json:"proxyResponse,omitempty"`
	Message               string                       `json:"message,omitempty"`
	Gateway               string                       `json:"gateway,omitempty"`
	Subscription          string                       `json:"subscription,omitempty"`
	Metadata              map[string]map[string]string `json:"metadata,omitempty"`
	Host                  string                       `json:"host,omitempty"`
}
