/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// Subscription struct for Subscription
type Subscription struct {
	Id           string      `json:"id,omitempty"`
	Api          Api         `json:"api,omitempty"`
	Plan         Plan        `json:"plan,omitempty"`
	Application  Application `json:"application,omitempty"`
	Status       string      `json:"status,omitempty"`
	Request      string      `json:"request,omitempty"`
	Reason       string      `json:"reason,omitempty"`
	ProcessedAt  int64       `json:"processed_at,omitempty"`
	ProcessedBy  string      `json:"processed_by,omitempty"`
	SubscribedBy User        `json:"subscribed_by,omitempty"`
	StartingAt   int64       `json:"starting_at,omitempty"`
	EndingAt     int64       `json:"ending_at,omitempty"`
	CreatedAt    int64       `json:"created_at,omitempty"`
	UpdatedAt    int64       `json:"updated_at,omitempty"`
	ClosedAt     int64       `json:"closed_at,omitempty"`
	PausedAt     int64       `json:"paused_at,omitempty"`
	ClientId     string      `json:"client_id,omitempty"`
}
