/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UpdateSubscriptionEntity struct for UpdateSubscriptionEntity
type UpdateSubscriptionEntity struct {
	Id         string `json:"id,omitempty"`
	StartingAt int64  `json:"starting_at,omitempty"`
	EndingAt   int64  `json:"ending_at,omitempty"`
}
