/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// MonitoringCpu struct for MonitoringCpu
type MonitoringCpu struct {
	PercentUse  int32                             `json:"percent_use,omitempty"`
	LoadAverage map[string]map[string]interface{} `json:"load_average,omitempty"`
}
