/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// NewApiEntity struct for NewApiEntity
type NewApiEntity struct {
	Name        string   `json:"name"`
	Version     string   `json:"version"`
	Description string   `json:"description"`
	ContextPath string   `json:"contextPath"`
	Endpoint    string   `json:"endpoint"`
	Groups      []string `json:"groups,omitempty"`
	Paths       []string `json:"paths,omitempty"`
}
