/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// PortalApis struct for PortalApis
type PortalApis struct {
	TilesMode          Enabled `json:"tilesMode,omitempty"`
	ViewMode           Enabled `json:"viewMode,omitempty"`
	ApiHeaderShowTags  Enabled `json:"apiHeaderShowTags,omitempty"`
	ApiHeaderShowViews Enabled `json:"apiHeaderShowViews,omitempty"`
}
