/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// UserMembershipList struct for UserMembershipList
type UserMembershipList struct {
	Memberships []UserMembership                             `json:"memberships,omitempty"`
	Metadata    map[string]map[string]map[string]interface{} `json:"metadata,omitempty"`
}
