/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// RoleMappingEntity struct for RoleMappingEntity
type RoleMappingEntity struct {
	Condition  string `json:"condition,omitempty"`
	Portal     string `json:"portal,omitempty"`
	Management string `json:"management,omitempty"`
}
