/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// SearchLogResponse struct for SearchLogResponse
type SearchLogResponse struct {
	Total    int64                        `json:"total,omitempty"`
	Logs     []LogItem                    `json:"logs,omitempty"`
	Metadata map[string]map[string]string `json:"metadata,omitempty"`
}
