/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// MemberRoleEntity struct for MemberRoleEntity
type MemberRoleEntity struct {
	Scope string `json:"scope,omitempty"`
	Name  string `json:"name,omitempty"`
}
