/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// DictionaryEntity struct for DictionaryEntity
type DictionaryEntity struct {
	Id          string                   `json:"id,omitempty"`
	Name        string                   `json:"name,omitempty"`
	Description string                   `json:"description,omitempty"`
	Type        string                   `json:"type,omitempty"`
	State       string                   `json:"state,omitempty"`
	Properties  map[string]string        `json:"properties,omitempty"`
	Provider    DictionaryProviderEntity `json:"provider,omitempty"`
	Trigger     DictionaryTriggerEntity  `json:"trigger,omitempty"`
	CreatedAt   int64                    `json:"created_at,omitempty"`
	UpdatedAt   int64                    `json:"updated_at,omitempty"`
	DeployedAt  int64                    `json:"deployed_at,omitempty"`
}
