/*
 * Gravitee.io - Rest API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.22.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graviteeapim

// MetadataPage struct for MetadataPage
type MetadataPage struct {
	Content       []map[string]interface{} `json:"content,omitempty"`
	Metadata      map[string]string        `json:"metadata,omitempty"`
	PageElements  int64                    `json:"pageElements,omitempty"`
	PageNumber    int32                    `json:"pageNumber,omitempty"`
	TotalElements int64                    `json:"totalElements,omitempty"`
}
